create table zxjy_dwb.dwb_intention_detail(
-- 客户意向事实表
    id                          int    comment '意向id',
    create_date_time            string comment '创建时间',
    update_date_time            string comment '最后更新时间',
    deleted                     int comment '是否被删除（禁用）',
    customer_id                 int comment '所属客户id',
    first_id                    int comment '第一条客户关系id',
    belonger                    int comment '归属人',
    belonger_name               string comment '归属人姓名',
    initial_belonger            int comment '初始归属人',
    distribution_handler        int comment '分配处理人',
    business_scrm_department_id int comment '归属部门',
    last_visit_time             string comment '最后回访时间',
    next_visit_time             string comment '下次回访时间',
    origin_type                 string comment '数据来源',
    itcast_school_id            int comment '校区Id',
    itcast_subject_id           int comment '学科Id',
    intention_study_type        string comment '意向学习方式',
    anticipat_signup_date       string comment '预计报名时间',
    `level`                       string comment '客户级别',
    creator                     int comment '创建人',
    current_creator             int comment '当前创建人：初始==创建人，当在公海拉回时为 拉回人',
    creator_name                string comment '创建者姓名',
    origin_channel              string comment '来源渠道',
    `comment`                     string comment '备注',
    first_customer_clue_id      int comment '第一条线索id',
    last_customer_clue_id       int comment '最后一条线索id',
    process_state               string comment '处理状态',
    process_time                string comment '处理状态变动时间',
    payment_state               string comment '支付状态',
    payment_time                string comment '支付状态变动时间',
    signup_state                string comment '报名状态',
    signup_time                 string comment '报名时间',
    notice_state                string comment '通知状态',
    notice_time                 string comment '通知状态变动时间',
    lock_state                  int comment '锁定状态',
    lock_time                   string comment '锁定状态修改时间',
    itcast_clazz_id             int comment '所属ems班级id',
    itcast_clazz_time           string comment '报班时间',
    payment_url                 string comment '付款链接',
    payment_url_time            string comment '支付链接生成时间',
    ems_student_id              int comment 'ems的学生id',
    delete_reason               string comment '删除原因',
    deleter                     int comment '删除人',
    deleter_name                string comment '删除人姓名',
    delete_time                 string comment '删除时间',
    course_id                   int comment '课程ID',
    course_name                 string comment '课程名称',
    delete_comment              string comment '删除原因说明',
    close_state                 string comment '关闭装填',
    close_time                  string comment '关闭状态变动时间',
    appeal_id                   int comment '申诉id',
    tenant                      int comment '租户',
    total_fee                   string comment '报名费总金额',
    belonged                    int comment '小周期归属人',
    belonged_time               string comment '归属时间',
    belonger_time               string comment '归属时间',
    transfer                    int comment '转移人',
    transfer_time               string comment '转移时间',
    follow_type                 string comment '分配类型，0-自动分配，1-手动分配，2-自动转移，3-手动单个转移，4-手动批量转移，5-公海领取',
    transfer_bxg_oa_account     string comment '转移到博学谷归属人OA账号',
    transfer_bxg_belonger_name  string comment '转移到博学谷归属人OA姓名',
-- 学员信息表
    student_id                int comment  '学员id',
    idcard                   string comment '身份证号',
    birth_year               int comment '出生年份',
    area                     string comment '所在区域',
    leave_school_date        string comment '离校时间',
    graduation_date          string comment '毕业时间',
    bxg_student_id           string comment '博学谷学员ID，可能未关联到，不存在',
    md_id                    int comment '中台id',
-- 线索信息表
    customer_relationship_id int comment '客户关系id',
    session_id               string comment '七陌会话id',
    sid                      string comment '访客id',
    `status`                   string comment '状态（undeal待领取 deal 已领取 finish 已关闭 changePeer 已流转）',
    `user`                   string comment '所属坐席',
    create_time              string comment '七陌创建时间',
    platform                 string comment '平台来源 （pc-网站咨询|wap-wap咨询|sdk-app咨询|weixin-微信咨询）',
    s_name                   string comment '用户名称',
    seo_source               string comment '搜索来源',
    seo_keywords             string comment '关键字',
    ip                       string comment 'IP地址',
    referrer                 string comment '上级来源页面',
    from_url                 string comment '会话来源页面',
    landing_page_url         string comment '访客着陆页面',
    url_title                string comment '咨询页面title',
    to_peer                  string comment '所属技能组',
    manual_time              string comment '人工开始时间',
    begin_time               string comment '坐席领取时间 ',
    reply_msg_count          int comment '客服回复消息数',
    total_msg_count          int comment '消息总数',
    msg_count                int comment '客户发送消息数',
    finish_reason            string comment '结束类型',
    finish_user              string comment '结束坐席',
    end_time                 string comment '会话结束时间',
    platform_description     string comment '客户平台信息',
    browser_name             string comment '浏览器名称',
    os_info                  string comment '系统名称',
    country                  string comment '所在国家',
    province                 string comment '省',
    city                     string comment '城市',
    name                     string comment '客户姓名',
    phone                    string comment '手机号',
    itcast_school            string comment '校区',
    itcast_subject           string comment '学科',
    wechat                   string comment '微信',
    qq                       string comment 'qq号',
    email                    string comment '邮箱',
    gender                   string comment '性别',
    information_way          string comment '资讯方式',
    working_years            string comment '开始工作时间',
    technical_directions     string comment '技术方向',
    customer_state           string comment '当前客户状态',
    valid                    int comment '该线索是否是网资有效线索',
    clue_state               string comment '线索状态',
    scrm_department_id       int comment 'SCRM内部部门id',
    superior_url             string comment '诸葛获取上级页面URL',
    superior_source          string comment '诸葛获取上级页面URL标题',
    landing_url              string comment '诸葛获取着陆页面URL',
    landing_source           string comment '诸葛获取着陆页面URL来源',
    info_url                 string comment '诸葛获取留咨页URL',
    info_source              string comment '诸葛获取留咨页URL标题',
    zhuge_session_id         string,
    is_repeat                int comment '是否重复线索(手机号维度) 0:正常 1：重复',
    activity_id              string comment '活动id',
    activity_name            string comment '活动名称',
    shunt_mode_id            int comment '匹配到的技能组id',
    shunt_employee_group_id  int comment '所属分流员工组',
-- 校区信息表
    school_id                string comment '学校id',
    school_address_name             string comment '校区名称',
    school_address_code             string comment '校区名称编码',
-- 学科信息表
    subject_id               string comment '学科id',
    subject_name             string comment '学科名称',
    subject_code             string comment '学科编码',
-- 员工信息表
    employee_id         string comment '员工id',
    real_name           string comment '员工的真实姓名',
    department_id       string comment 'OA中的部门编号，有负值',
    department_name     string comment 'OA中的部门名',
    remote_login        int comment '员工是否可以远程登录',
    job_number          string comment '员工工号',
    cross_school        int comment '是否有跨校区权限',
    last_login_date     string comment '最后登录日期',
    leave_office        int comment '离职状态',
    leave_office_time   string comment '离职时间',
    reinstated_time     string comment '复职时间',
    superior_leaders_id int comment '上级领导ID',
    tdepart_id          int comment '直属部门',
    ems_user_name       string,
-- 部门信息表
    departments_id   int comment '部门id',
    departments_name  string comment '部门名称',
    parent_id        int comment '父部门id',
    id_path          string comment '编码全路径',
    tdepart_code     int comment '直属部门',
    depart_level     int comment '部门层级',
    depart_sign      int comment '部门标志，暂时默认1',
    depart_line      int comment '业务线，存储业务线编码',
    depart_sort      int comment '排序字段',
    disable_flag     int comment '禁用标志',
    dt string            comment '分区字段'
)
COMMENT '意向与线索明细宽表'
row format delimited fields terminated by '\t'
stored as orc
tblproperties ('orc.compress' = 'SNAPPY');

insert overwrite table zxjy_dwb.dwb_intention_detail
select
    cr.id,
    cr.create_date_time,
    cr.update_date_time,
    cr.deleted,
    cr.customer_id,
    cr.first_id,
    cr.belonger,
    cr.belonger_name,
    cr.initial_belonger,
    cr.distribution_handler,
    cr.business_scrm_department_id,
    cr.last_visit_time,
    cr.next_visit_time,
    cr.origin_type,
    cr.itcast_school_id,
    cr.itcast_subject_id,
    cr.intention_study_type,
    cr.anticipat_signup_date,
    cr.level,
    cr.creator,
    cr.current_creator,
    cr.creator_name,
    cr.origin_channel,
    cr.comment,
    cr.first_customer_clue_id,
    cr.last_customer_clue_id,
    cr.process_state,
    cr.process_time,
    cr.payment_state,
    cr.payment_time,
    cr.signup_state,
    cr.signup_time,
    cr.notice_state,
    cr.notice_time,
    cr.lock_state,
    cr.lock_time,
    cr.itcast_clazz_id,
    cr.itcast_clazz_time,
    cr.payment_url,
    cr.payment_url_time,
    cr.ems_student_id,
    cr.delete_reason,
    cr.deleter,
    cr.deleter_name,
    cr.delete_time,
    cr.course_id,
    cr.course_name,
    cr.delete_comment,
    cr.close_state,
    cr.close_time,
    cr.appeal_id,
    cr.tenant,
    cr.total_fee,
    cr.belonged,
    cr.belonged_time,
    cr.belonger_time,
    cr.transfer,
    cr.transfer_time,
    cr.follow_type,
    cr.transfer_bxg_oa_account,
    cr.transfer_bxg_belonger_name,
    c.id as student_id,
    c.idcard,
    c.birth_year,
    c.area,
    c.leave_school_date,
    c.graduation_date,
    c.bxg_student_id,
    c.md_id,
    cc.customer_relationship_id,
    cc.session_id,
    cc.sid,
    cc.status,
    cc.`user`,
    cc.create_time,
    cc.platform,
    cc.s_name,
    cc.seo_source,
    cc.seo_keywords,
    cc.ip,
    cc.referrer,
    cc.from_url,
    cc.landing_page_url,
    cc.url_title,
    cc.to_peer,
    cc.manual_time,
    cc.begin_time,
    cc.reply_msg_count,
    cc.total_msg_count,
    cc.msg_count,
    cc.finish_reason,
    cc.finish_user,
    cc.end_time,
    cc.platform_description,
    cc.browser_name,
    cc.os_info,
    cc.country,
    cc.province,
    cc.city,
    cc.name,
    cc.phone,
    cc.itcast_school,
    cc.itcast_subject,
    cc.wechat,
    cc.qq,
    cc.email,
    cc.gender,
    cc.information_way,
    cc.working_years,
    cc.technical_directions,
    cc.customer_state,
    cc.valid,
    cc.clue_state,
    cc.scrm_department_id,
    cc.superior_url,
    cc.superior_source,
    cc.landing_url,
    cc.landing_source,
    cc.info_url,
    cc.info_source,
    cc.zhuge_session_id,
    cc.is_repeat,
    cc.activity_id,
    cc.activity_name,
    cc.shunt_mode_id,
    cc.shunt_employee_group_id,
    `is`.id as school_id,
    `is`.name as school_address_name,
    `is`.code as school_address_code,
    it.id as subject_id,
    it.name as subject_name,
    it.code as subject_code,
    fe.id as employee_id,
    fe.real_name,
    fe.department_id,
    fe.department_name,
    fe.remote_login,
    fe.job_number,
    fe.cross_school,
    fe.last_login_date,
    fe.leave_office,
    fe.leave_office_time,
    fe.reinstated_time,
    fe.superior_leaders_id,
    fe.tdepart_id,
    fe.ems_user_name,
    sd.id as departments_id,
    sd.name as departments_name,
    sd.parent_id,
    sd.id_path,
    sd.tdepart_code,
    sd.depart_level,
    sd.depart_sign,
    sd.depart_line,
    sd.depart_sort,
    sd.disable_flag,
    cr.dt
from zxjy_dwd.dwd_fact_customer_relationship cr
-- 学员信息表
left join zxjy_dwd.dwd_fact_customer c on cr.customer_id = c.id
-- 线索信息表
left join zxjy_dwd.dwd_fact_customer_clue cc on cr.id = cc.customer_relationship_id
-- 校区维度
left join zxjy_dwd.dwd_dim_ods_itcast_school `is` on cr.itcast_school_id = `is`.id
-- 学科维度
left join zxjy_dwd.dwd_dim_itcast_subject it on cr.itcast_subject_id = it.id
-- 员工维度表
left join zxjy_dwd.dwd_fact_employee fe on cr.creator = fe.id
-- 员工部门名称
left join zxjy_dwd.dwd_dim_scrm_department sd on fe.tdepart_id = sd.id ;